name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v -o dietly-pb ./...

      - name: Test
        run: go test -v ./...

      - name: Create ZIP
        run: zip dietly-pb.zip dietly-pb

      - name: Publish Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: dietly-pb.zip
          tag_name: v${{ github.run_number }}
          prerelease: false
